apiVersion: v1
kind: ServiceAccount
metadata:
  name: compute-fabric-workload
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::882640845424:role/ai-compute-fabric-dev-artifact-workload-role
